# Generated by Django 4.1.7 on 2023-03-08 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('caption', models.TextField(max_length=5000, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
